In [1]:
import numpy as np 

print(np.__version__)

1.26.4


In [29]:
arr = np.array([[2,3,4,5,6],[4,4,5,6,43]])

print(arr*2)

print(arr.shape)
arr.ndim

#single dimenstional array which can be used in order to do simple multiplications

[[ 4  6  8 10 12]
 [ 8  8 10 12 86]]
(2, 5)


2

In [ ]:
# will be dealing with multidimenstional arrays 
array = np.array ([[[1,2,3,6]],[[1, '','',4 ]],[[1,2,3,4]],
                   [[1,2,3,6]],[[1, '','',4 ]],[[1,2,3,4]],
                   [[1,2,3,6]],[[1, '','',4 ]],[[1,2,3,4]]])

print(array.ndim)
print(array.shape)



3
(9, 1, 4)


## holy moly theres a clear differentiation betweeen 1d,2d,3d arrays which i totally forgot -> in short 

### 1. Array([1,2,3,4]) -> is id 
### 2. array([1,23,45],[])-> wont work as this just 1d , one row -> what would work is array([[12,3,4,5],[544,4,5,5]])
### 3. array([[[124,355,567]],[[1,23,5,4,5]]]) -> this is a 3d array 

In [43]:
word = array[1,0,3] + array[2,0,2]

print(word)# a clear understanding between rows and columns has been understood where the rows and columns are , every dimension has its own speicfic thing  like a block , row , column 

# given i have taken a [[[ approach where i divided each list into block therefore i have to put 0 in row ]]]




43


### the above is a multidimentional indexing which is damn faster then chain indexing [0][0][0] -> which is present in python 
### So the Array [[],[],[]]- this is one dimentional and has o block , 3 row , o column if we look at the shape pov in a 3 dimentional thing 

In [68]:
ninja = np.array([[1,2,3,4],
                  [4,5,6,7],
                  [9,10,11,12],
                  [15,16,17,18]])

print(ninja[1::3]) # basic slicing through arrays and if u wanna print reverse just use [::-1] -> prints everything in reverse order and always the place at which it needs to stop it will not include that 

print ( ninja[:,2]+ ninja[:,3]) #column slicing can also be done instead of concat its just numbers 
print(ninja[0:2,0:3])

[[4 5 6 7]]
[ 7 13 23 35]
[[1 2 3]
 [4 5 6]]
