In [69]:
import numpy as np 

print(np.__version__)

1.26.4


In [70]:
arr = np.array([[2,3,4,5,6],[4,4,5,6,43]])

print(arr*2)

print(arr.shape)
arr.ndim

#single dimenstional array which can be used in order to do simple multiplications

[[ 4  6  8 10 12]
 [ 8  8 10 12 86]]
(2, 5)


2

In [71]:
# will be dealing with multidimenstional arrays 
array = np.array ([[[1,2,3,6]],[[1, '','',4 ]],[[1,2,3,4]],
                   [[1,2,3,6]],[[1, '','',4 ]],[[1,2,3,4]],
                   [[1,2,3,6]],[[1, '','',4 ]],[[1,2,3,4]]])

print(array.ndim)
print(array.shape)



3
(9, 1, 4)


## holy moly theres a clear differentiation betweeen 1d,2d,3d arrays which i totally forgot -> in short 

### 1. Array([1,2,3,4]) -> is id 
### 2. array([1,23,45],[])-> wont work as this just 1d , one row -> what would work is array([[12,3,4,5],[544,4,5,5]])
### 3. array([[[124,355,567]],[[1,23,5,4,5]]]) -> this is a 3d array 

In [72]:
word = array[1,0,3] + array[2,0,2]

print(word)# a clear understanding between rows and columns has been understood where the rows and columns are , every dimension has its own speicfic thing  like a block , row , column 

# given i have taken a [[[ approach where i divided each list into block therefore i have to put 0 in row ]]]




43


### the above is a multidimentional indexing which is damn faster then chain indexing [0][0][0] -> which is present in python 
### So the Array [[],[],[]]- this is one dimentional and has o block , 3 row , o column if we look at the shape pov in a 3 dimentional thing 

In [73]:
ninja = np.array([[1,2,3,4],
                  [4,5,6,7],
                  [9,10,11,12],
                  [15,16,17,18]])

print(ninja[1::3]) # basic slicing through arrays and if u wanna print reverse just use [::-1] -> prints everything in reverse order and always the place at which it needs to stop it will not include that 

print ( ninja[:,2]+ ninja[:,3]) #column slicing can also be done instead of concat its just numbers 
print(ninja[0:2,0:3])

[[4 5 6 7]]
[ 7 13 23 35]
[[1 2 3]
 [4 5 6]]


In [83]:
ayo = np.array([1,2,3,4])

# today will be going through Scalar arthemetic operations ( linear algebra term)

print ( ayo +1)
print ( ayo -3)
print (ayo *4)
print (ayo /4)
# to increase a element to power of 5 
print (ayo**5)

# element wise arthimetic functions can also be done 

dawg = np.array([1,2,3,42])

print (ayo+dawg)
print ( ayo - dawg)
print (ayo ** dawg)

[2 3 4 5]
[-2 -1  0  1]
[ 4  8 12 16]
[0.25 0.5  0.75 1.  ]
[   1   32  243 1024]
[ 2  4  6 46]
[  0   0   0 -38]
[ 1  4 27  0]


In [91]:
# vector operations 

# now u might be asking me whats a vector , vector is a single dimention , where as scalar is a single value remmeber this as its so damn crucial for deep learning and nlp 

print (np.floor(ayo/3))
print (np.round(ayo/2))
print (np.ceil(ayo*2 /4))

radii = ayo 

print ( np.pi * radii **2)

# Theres the lord of operators comparison operators  i dont know why i feel like i have done this before but i cant remember where 

print ( ayo == dawg)
print ( ayo <= dawg)
print ( ayo >= dawg)
print (ayo < dawg)

# we can assign conditional assignment that way if there's anything u would like to recognise u could do it instantly 
ayo[ayo<dawg] = 0 
print ( ayo)

[0. 0. 1. 1.]
[0. 1. 2. 2.]
[1. 1. 2. 2.]
[ 3.14159265 12.56637061 28.27433388 50.26548246]
[ True  True  True False]
[ True  True  True  True]
[ True  True  True False]
[False False False  True]
[1 2 3 0]


## Broadcasting 

### 1. Broadcasting helps arrays match dimensions so that we could fit in different shapes of arrays to match larger arrays ( i knew there would be a built in function like this comeone , how does normal np.array not do stuff that aint possible)

### 2. For Broadcasting to work theres absolutely an important term that needs to happen that is 
####        a. One of the values should match or 
####        b. One of the values should be one in order to Broadcast but if the rows are matching but columns arent then we cant , as the main purpose is to virtually increase the dimension of these arrays 

In [ ]:
# Broadcasting 

number = np.array ([[1,2,3,4],
                    [2,3,4,5],
                    [5,6,7,8]])

two = np.array ([[1,2,3,4,], [1,2,3,0], [1,2,3,0]])

print ( number.shape)
print (two.shape)

#lets see if broadcasting happens here 

print ( number * two)

# as we can see the shape is (3,4) , (3,5) -> even though the rows are matching but the dimentions or numbers aint matching , now when i updated the array its at shape of (3,4) for both yet its not happening cause theres a null value i g? ( hence proved , when i removed the placeholder it ended up showing the array )

(3, 4)
(3, 4)
[[ 1  4  9 16]
 [ 2  6 12  0]
 [ 5 12 21  0]]


In [105]:
# lets build a multiplicatio table for 100 numbers lol 

first_number = np . array ([1,2,3,4,5,6,7,8,9,10])

second_number = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print ( first_number * second_number)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## In short this is broadcasting , which alllows numpy to perform different operations on arrays with different shapes and from the above we can see that it should always be in form of alternate transpose i guess or have atleast 1 in either of the opposite sides to ensure that the broadcasting is done properly lol 

### anyways thats what i understood not sure when ill use this but for sure i would love to know how i could use damn binomial and normal distubution at this point , probability is something i always need to look into but anyways the above is a 10x10 matrix 

## The very next topic i am dealing with is Aggregate Functions 

In [114]:
doggo = np.array ([[1,2,3,4,5],
                   [6,7,8,9,10]])

print (np.sum(doggo))
print (np.mean(doggo))
print(np.std(doggo))
print (np.var(doggo))
print (np.min(doggo))
print(np.max(doggo))
print(np.argmax(doggo)) # returns the positio of the maximum value in array
print(np.argmin(doggo)) # returns the position of minimum value in array 
print (np.sum(doggo,axis = 1) ) # when axis is 1 it will sum up the values of rows and display as a list of those new value of array rows 
print (np.sum(doggo,axis=0))
print ( np.sum(doggo , axis = -1)) # these are the aggregate functions that return single value when we need them 

55
5.5
2.8722813232690143
8.25
1
10
9
0
[15 40]
[ 7  9 11 13 15]
[15 40]


## Given i have already use aggregate functions in sql , this just feels like a breeze but yeah moving on to filtering , there's a lot of functions in numpy for sure , will be going through the specific functions in w3 schools whenever i need em , the next topic is Filtering 

In [ ]:
ages = np.array([[1,2,3,4,5,6,44,2,4,5,2,5,24,5,45,24,542,5,54,5,4,4,4,5,5,4,455,3,34,5,5]])

adults = np.where(ages>18,ages,0) #basically i would have to fill in a replacement for the value to show how many adults are existing in this array but other than that replacement

print(adults)

[[  0   0   0   0   0   0  44   0   0   0   0   0  24   0  45  24 542   0
   54   0   0   0   0   0   0   0 455   0  34   0   0]]


### the boolean indexing is absolutely better than where clause cause this is slower than the boolean indexing and use this if u wanna preserve how this looks in the files 

### next stop is Random numbersss

In [139]:
rng = np.random.default_rng(seed = 1) # default rng will produce different random numbers in general  , also seed = 1 will reproduce the same numbers no matter whose using it

print(rng.integers(low =1, high = 55 , size = (44,2))) # 44 rows 2 columns lol this is insane hahaha 

flo = np.random.uniform(low = 1 ,high=3 , size = (33,5))

rng.shuffle(flo)

[[26 28]
 [41 52]
 [ 2  8]
 [45 52]
 [14 17]
 [47 23]
 [15 45]
 [14 23]
 [35 30]
 [ 5  2]
 [47 41]
 [46 30]
 [45 18]
 [25 43]
 [ 7 17]
 [ 7 25]
 [53  8]
 [21 22]
 [49 11]
 [28 15]
 [ 2 41]
 [ 4 16]
 [27 27]
 [ 7 53]
 [41 52]
 [ 5 40]
 [16 30]
 [50 15]
 [40  9]
 [18 53]
 [23 28]
 [16  7]
 [23 34]
 [25 42]
 [20 34]
 [42 50]
 [24  3]
 [39 29]
 [48 25]
 [20  4]
 [25 35]
 [42 47]
 [12 33]
 [44 15]]


In [142]:
rng = np.random.default_rng()

fruits = np.array(["kiwi","apple","guava","raspberry"])

fruits = rng.choice(fruits, size = (55,5))

print(fruits)



[['apple' 'kiwi' 'raspberry' 'apple' 'guava']
 ['kiwi' 'raspberry' 'kiwi' 'guava' 'guava']
 ['raspberry' 'raspberry' 'kiwi' 'guava' 'apple']
 ['guava' 'guava' 'raspberry' 'guava' 'apple']
 ['apple' 'kiwi' 'guava' 'apple' 'guava']
 ['apple' 'guava' 'kiwi' 'apple' 'raspberry']
 ['apple' 'kiwi' 'guava' 'guava' 'apple']
 ['guava' 'apple' 'guava' 'apple' 'kiwi']
 ['raspberry' 'apple' 'apple' 'apple' 'raspberry']
 ['raspberry' 'raspberry' 'kiwi' 'apple' 'kiwi']
 ['kiwi' 'apple' 'kiwi' 'kiwi' 'guava']
 ['raspberry' 'apple' 'guava' 'kiwi' 'apple']
 ['raspberry' 'apple' 'guava' 'raspberry' 'guava']
 ['kiwi' 'guava' 'apple' 'raspberry' 'apple']
 ['kiwi' 'guava' 'kiwi' 'apple' 'kiwi']
 ['apple' 'raspberry' 'apple' 'raspberry' 'apple']
 ['kiwi' 'kiwi' 'apple' 'guava' 'raspberry']
 ['guava' 'raspberry' 'raspberry' 'apple' 'guava']
 ['kiwi' 'kiwi' 'kiwi' 'kiwi' 'raspberry']
 ['apple' 'guava' 'raspberry' 'kiwi' 'guava']
 ['raspberry' 'guava' 'kiwi' 'kiwi' 'kiwi']
 ['kiwi' 'raspberry' 'raspberry' 'app